name: Flujo de trabajo para la práctica 5
on:
  workflow_dispatch:
  issues:
    types: [opened]
  project_card:
    types: [moved]
jobs:
  Acciones_en_Issues:
    runs-on: ubuntu-latest
    steps:
      - name: Crear un comentario
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets-GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hola ${{ github.event.issue.user.login }}, sigue trabajando así.
          emoji: '+1,heart'
      - name: Poner una etiqueta
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'set-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'bug'
